// Package web provides the production web application bundled with the server binary.
package web

import (
	"embed"
	"io/fs"
)

// embeddedDistribution is generated by the frontend build. Its absence is a compile-time error.
//
//go:embed dist
var embeddedDistribution embed.FS

// Dist exposes the built frontend with web/dist removed from its paths.
var Dist = distributionFS()

func distributionFS() fs.FS {
	dist, err := fs.Sub(embeddedDistribution, "dist")
	if err != nil {
		panic("open embedded frontend distribution: " + err.Error())
	}
	return dist
}
